### ISSUE TITLE
Consider choosing a license for the project?

### ISSUE THREAD

**Issue by hugocf** [goblindegook/irregular-apocalypse#1]
As per https://help.github.com/articles/licensing-a-repository/

> (…) without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

TIP _(and probably stating the obvious)_: You can just [create a new file](https://github.com/goblindegook/irregular-apocalypse/new/master) in GitHub, name if `LICENSE`, and GitHub’s web UI will offer templates to choose from.

**Comment by goblindegook** [comment]
I thought I had one. Added in d3100117a2b13595c994a842834b254ad49fc952.

Thanks for noticing!
